### ISSUE TITLE
attempt to build the demo collection is "killed"

### ISSUE THREAD

**Issue by scott2b** [MuckRock/sidekick#3]
This looks like maybe a resource limitation issue on my laptop? Not sure. Trying to build the demo collection per the README, and I see this:

```
❯ collection=amazon_instrument_reviews language=en docker compose -f build.yml run --rm preprocess
[+] Running 1/1
 ⠿ Network sidekick_default  Created                                                                                                                                 5.7s
GOT PARAMS {'collection': 'amazon_instrument_reviews', 'language': 'en'}
[00:00.00] Reading all text files
[00:59.84] Deriving counts over corpus (N=10261, avg words=90.18)
/usr/local/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
[01:01.21] Creating bigram model
[01:01.96] Spell-reducing the vocabulary (20551 to 30000)
[01:02.34] Deriving tf-idf on spell-reduced corpus
[01:05.35] Applying SVD to lower dimensionality of TF-IDF
[01:15.98] Loading embedding model
Killed
```

**Comment by mitchelljkotler** [comment]
This does take a lot of memory.  Your laptop is likely running out of memory.  How much memory does your laptop have?

**Comment by scott2b** [comment]
That was my initial thought -- I have 16GB RAM on a 2015 MacBook Pro -- but I have tried it with as few as 14 docs ... fewer than that and it won't run because there are too few docs compared to features for what appears to be either the tf-idf processing or perhaps some clustering algorithm.

**Comment by mitchelljkotler** [comment]
16GB should be enough RAM, you may need to allocate more RAM to docker, see the instructions here: https://github.com/MuckRock/sidekick#troubleshooting

Also, the large memory requirement is mostly due to loading the language embedding model, which is independent of how many documents you are using it on.

**Comment by scott2b** [comment]
This was it. I allocated 10GB to Docker, and the build was able to complete.
