### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by ninoppp** [MuckRock/sidekick#4]
Just a quick question: Is Sidekick specialized for English or do other languages work with the same quality?

**Comment by morisy** [comment]
Early tests show it seems to run fairly effectively in non-English languages, but we're hoping to do additional validation in the coming months. We have a hosted version on DocumentCloud now — if you have a use case and would like to try, we'd love to hear your experience either with this repository or the hosted version!

**Comment by ninoppp** [comment]
Cool, you might hear from me in a few months (hopefully)
